name: cy-tsl

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:
    
jobs:
  cy-tsl-parsing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download CY TSL
      run: curl --url="https://dec.dmrid.gov.cy/dmrid/dec/ws_dec.nsf/all/5064247FF4FC3DCCC2258506002EEA17/\$file/TSL-CY-sign.xml" --create-dirs -o ./CY/TSL_CY.xml
    - name: Create PR if needed
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        branch: cy-tsl
        delete-branch: true
        title: 'CY TSL'
