name: de-tsl

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:
    
jobs:
  de-tsl-parsing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download DE TSL
      run: curl https://tl.bundesnetzagentur.de/TL-DE.XML --create-dirs -o ./DE/TSL_DE.xml
    - name: Create PR if needed
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        branch: de-tsl
        delete-branch: true
        title: 'DE TSL'
