name: el-tsl

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:
    
jobs:
  el-tsl-parsing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download EL TSL
      run: curl https://www.eett.gr/tsl/EL-TSL.xml --create-dirs -o ./EL/TSL_EL.xml
    - name: Create PR if neeeed
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        branch: el-tsl
        delete-branch: true
        title: 'EL TSL'
