name: eu-lotl

on:
  schedule:
    - cron: '1 0 * * 1'
  workflow_dispatch:
    
jobs:
  eu-tsl-parsing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download EU TSL
      run: wget -O eu-lotl.xml https://ec.europa.eu/tools/lotl/eu-lotl.xml
    - name: Parse Country codes
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'eu-lotl.xml'
        xpath: "//*[local-name()='TSLLocation']"
    - name: Create PR if needed
      id: cpr
      uses: peter-evans/create-pull-request@v5
