name: eu-lotl

on:
  schedule:
    - cron: '1 0 * * 1'
  workflow_dispatch:
    
jobs:
  eu-tsl-parsing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download EU TSL
      uses: suisei-cn/actions-download-file@v1.4.0
      id: downloadfile  # Remember to give an ID if you need the output
      with:
        url: "https://ec.europa.eu/tools/lotl/eu-lotl.xml"
        target: eu-lotl.xml
        retry-times: 3
    - name: Parse Country codes
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'eu-lotl.xml'
        xpath: "//*[local-name()='TSLLocation']"
    - name: Create PR if needed
      id: cpr
      uses: peter-evans/create-pull-request@v5
