name: eu-lotl

on:
  schedule:
    - cron: '1 0 * * 1'
  workflow_dispatch:
    
jobs:
  eu-tsl-parsing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download EU TSL
      run: wget -O eu-lotl.xml https://ec.europa.eu/tools/lotl/eu-lotl.xml
    - name: Install xml_grep
      run: sudo apt install -y xml-twig-tools
    - name: Grep pivots
      run: xml_grep '//SchemeInformationURI/URI' eu-lotl.xml --text_only > eu-lotl-pivot.txt
    - name: Get TSL version
      id: getxml
      uses: mavrosxristoforos/get-xml-info@2.0
      with:
        xml-file: 'eu-lotl.xml'
        xpath: "/*[local-name()='TrustServiceStatusList']/*[local-name()='SchemeInformation']/*[local-name()='TSLSequenceNumber']"
    - name: Print TSL version
      run: echo "${{ steps.getxml.outputs.info }}"
    - name: Create PR if needed
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        branch: eu-tsl
        delete-branch: true
        title: 'EU TSL - Version ${{ steps.getxml.outputs.info }}'
