name: fi-tsl

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:
    
jobs:
  fi-tsl-parsing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download FI TSL
      run: curl https://dp.trustedlist.fi/fi-tl.xml --create-dirs -o ./FI/TSL_FI.xml
    - name: Create PR if neeeed
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        branch: fi-tsl
        delete-branch: true
        title: 'FI TSL'
