name: Get TSL version
on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'AT/TSL_AT.xml'
        xpath: "//*[local-name()='TSLSequenceNumber']/text()"
    - name: Print vertion
      run: echo "${{ steps.getxml.outputs.info }}"
