name: is-tsl

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:
    
jobs:
  is-tsl-parsing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download IS TSL
      run: curl -L --url "https://www.fjarskiptastofa.is/library/skrar/tsl/tsl.xml" --create-dirs -o ./IS/TSL_IS.xml
    - name: Create PR if neeeed
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        branch: is-tsl
        delete-branch: true
        title: 'IS TSL'
