name: lv-tsl

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:
    
jobs:
  lv-tsl-parsing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download LV TSL
      run: curl -L --url "https://trustlist.gov.lv/tsl/latvian-tsl.xml" --create-dirs -o ./LV/TSL_LV.xml
    - name: Create PR if neeeed
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        branch: lv-tsl
        delete-branch: true
        title: 'LV TSL'
