on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  changed-files:
    runs-on: ubuntu-latest
    needs: pr_commented
    steps:
      - uses: ankitjain28may/list-files-in-pr@v1.0
        id: list-files
        with:
          githubToken: ${{ github.token }}
          outputFormat: 'space-delimited'
      - run: |
          for file in ${{ steps.list-files.outputs.pullRequestFiles }}; do
            echo "Changed Files - ${file}."
          done

  xml-linters:
    runs-on: ubuntu-latest
    needs: pr_commented
    steps:
      - name: Validate TSL using XML schema
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./SK/TSL_SK.xml
          xml-schema-file: ./ValidationSchemas/ts_119612v020201_201601xsd.xsd
