on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  xml-linters:
    runs-on: ubuntu-latest
    needs: pr_commented
    if: ${{needs.changedfiles.outputs.xml}}
    steps:
      - name: Validate TSL using XML schema
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./SK/TSL_SK.xml
          xml-schema-file: ./ValidationSchemas/ts_119612v020201_201601xsd.xsd
