on: pull_request

jobs:
  changed-files:
    runs-on: ubuntu-latest
    steps:
     - id: files
       uses: jitterbit/get-changed-files@v1
     - run: |
         for changed_file in ${{ steps.files.outputs.added }}; do
           echo "Do something with this ${changed_file}."
         done

  xml-linters:
    runs-on: ubuntu-latest
    needs: changed-files
    steps:
      - name: Validate TSL using XML schema
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ${{ needs.changed-files.outputs.added }}
          xml-schema-file: ./ValidationSchemas/ts_119612v020201_201601xsd.xsd
