name: TSL-validation

on: 
  pull_request:
    paths:
      - '**.xml'
  workflow_dispatch:


jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.xml }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=xml::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .xml$ | xargs)"
  lint:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.xml}}
    steps:
      - name: echo changed files
        run: echo ${{needs.changedfiles.outputs.xml}}

  xml-linters:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Validate TSL using XML schema
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ${{needs.changedfiles.outputs.xml}}
          xml-schema-file: ./ValidationSchemas/ts_119612v020201_201601xsd.xsd
