name: TSL-validation

on: 
  pull_request:
    paths:
      - '**.xml'
  workflow_dispatch:

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Enable annotations for validation errors and warnings
      uses: korelstar/xmllint-problem-matcher@v1
    - name: Validate TSL using XML schema
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./SK/TSL_SK.xml
        xml-schema-file: ./ValidationSchemas/ts_119612v020201_201601xsd.xsd
