name: xml check
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: install xml_grep
      run: sudo apt install -y xml-twig-tools
    - name: grep pivots
      run: xml_grep '//SchemeInformationURI/URI' eu-lotl.xml --text-only
    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'eu-lotl.xml'
        xpath: "/*[local-name()='SchemeInformation']/*[local-name()='SchemeInformationURI']/*[local-name()='URI']/text()"
    - name: Pivot URIs
      run: echo "${{ steps.getxml.outputs.info }}"
