name: xml check
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  xml-val-check:        
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Get changed XML files
        id: changed
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }} | grep ".xml$" > files.txt || true

      - name: Validate changed XML files
        run: |
          SCHEMA="ValidationSChemas/ts_119612v020201_201601xsd.xsd"

          if [ ! -s files.txt ]; then
            echo "No XML files changed."
            exit 0
          fi

          while read file; do
            echo "Validating $file"
            xmllint --noout --schema $SCHEMA $file
          done < files.txt
